spring:
  application:
    name: User-Login
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true #注册服务使用ip
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/