##  Dockerfile文件格式

# This dockerfile uses the ubuntu image
# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..
 
# 1、第一行必须指定 基础镜像信息
FROM ubuntu
 
# 2、维护者信息
MAINTAINER elchoyang elcho@qq.com
 
# 3、镜像操作指令
RUN docker pull mysql:5.5
RUN docker pull phpmyadmin/phpmyadmin
RUN docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=123456 -d mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
RUN docker run --name myadmin -d --link mysql_db_server:db -p 8080:80 phpmyadmin/phpmyadmin
 
#开启80端口
EXPOSE 80

# 4、容器启动执行指令
CMD mysql -u root -p
CMD 123456
CMD create database [IF NOT EXISTS] sba;

